import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import hero from '../../public/images/profile/hero.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'
import { LinkArrow } from '@/components/Icons'



export default function Home() {
  return (
    <>
      <Head>
        <title>CJ Portfolio</title>
        <meta name="Portfolio Home Page" content="Generated by create next app" />
      </Head>

      <TransitionEffect/>  

      <main className='flex items-center text-dark dark:text-light w-full min-h-screen'>
        <Layout className='pt-0 sm:pt-8 md:pt-16'> 
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={hero} alt="cjpanda" className='w-full h-auto lg:hidden md:inline-block md:w-full' priority sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw" />
            </div>

            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center '>
              <AnimatedText text="Welcome To My Portfolio." className='!text-7xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                I am a skilled and motivated fullstack developer committed to crafting flawless web applications. Dive into my portfolio showcasing cutting-edge projects built with the latest web development technologies.
              </p>

              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href='/Resume.pdf' target={"-blank"}
                className='flex items-center bg-dark dark:bg-light dark:text-dark  text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-purple-900 hover:dark:bg-purple-900 hover:text-light hover:dark:text-light hover:border-transparent border-2 border-solid border-transparent
                hover:border-dark md:p-2 md:px-4 md:text-base'
                download={true}
                >Download CV 
                </Link>
                <Link href='/contact' className='ml-4 text-lg font-medium capitalize dark:text-light text-dark underline md:text-base'>Contact Me</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  )
}
